# Generated by Django 5.1.3 on 2024-12-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_wastereport_user_and_more'),
        ('waste', '0010_alter_wastereport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereportapproval',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='waste.wastereport'),
        ),
        migrations.AlterField(
            model_name='wastereportapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='WasteReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.wastereportapproval')),
            ],
        ),
        migrations.DeleteModel(
            name='WasteReport',
        ),
    ]
