# Generated by Django 5.1.3 on 2024-11-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_wastereport_description_wastereport_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wastereport',
            name='priority',
        ),
        migrations.AddField(
            model_name='wastereport',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='nearby_landmarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
