# Generated by Django 5.1.3 on 2024-12-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0008_wastereport_description_wastereport_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
