# Generated by Django 5.1.3 on 2024-12-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0011_reportsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='photo_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='ReportSubmission',
        ),
    ]
