# Generated by Django 5.1.3 on 2024-12-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0012_wastereport_photo_hash_delete_reportsubmission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
